### ISSUE TITLE
tox checks should not apply to test files

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-project-template#24]
I made a project using this template

When I ran tox it "corrected" a bunch of OWL files in my tests/input folder. I don't want these corrected. By all means we should fix the ontologies upstream but in general I don't want test files touched!

**Comment by hrshdhgd** [comment]
The `tox.ini` should have `--skip` param to take care of it since this may be project specific?

**Comment by cmungall** [comment]
Are you back? :-)

I think we want to err on the side of standardization and gently
encouraging the same dir layouts etc. Make tests/input the standard for
test data, tests/output for outputs. People can always tweak after the fact.
