### ISSUE TITLE
Hyphens or underscores in project name?

### ISSUE THREAD

**Issue by oneilsh** [monarch-initiative/monarch-project-template#4]
Cool project! I gave it a try using a project name with hyphens in it, but I'm getting stuck at the 'run' step. On setup it prompted that the package name would replace -'s with _'s which was ok with me, but here's what I see with the run step:

```
$ oai-monarch-plugin run
  File "/Users/oneils/Library/Caches/pypoetry/virtualenvs/oai-monarch-plugin-TfjMhMJ8-py3.11/bin/oai-monarch-plugin", line 3
    from oai-monarch-plugin.cli import main
            ^
SyntaxError: invalid syntax
```

Trying `oai_monarch_plugin run` was a command-not-found.

I'm not very familiar with poetry, perhaps I am just holding it wrong :)

**Comment by cmungall** [comment]
hmm, that is odd, it should have replaced the hyphens..

**Comment by hrshdhgd** [comment]
I have fixed this issue. Please confirm @oneilsh .

**Comment by cmungall** [comment]
I think @oneilsh had a one time project creation task. I don't see a PR linked here @hrshdhgd ?

**Comment by hrshdhgd** [comment]
I had fixed the issue but didn't see the issue until later: https://github.com/monarch-initiative/monarch-project-template/pull/5
